# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

filter_secrets: false
language: node_js

matrix:
  include:
    - name: Linux
      os: linux
      addons:
        firefox: latest
        chrome: stable

    - name: MacOS
      os: osx
      addons:
        firefox: latest
        chrome: stable

    - name: Windows (via SauceLabs)
      os: linux
      env: KARMA_PLATFORM=win32

before_script:
  # Link the package to itself (so Karma and Mocha can find it)
  - npm link
  - npm link karma-host-environment

  - npm run lint
  - npm run build

script:
  - npm run coverage

after_success:
  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: Deploy
      name: Publish to npm
      script: npm run build
      after_success: true
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
          branch: master
